HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 HF_HUB_OFFLINE=1 accelerate launch train_text_to_image_lora.py \
  --pretrained_model_name_or_path="/home/ralur/MACE-Update/saved_model/LoRA_fusion_model" \
  --train_data_dir="/home/ralur/.cache/huggingface/hub/datasets/adam_sandler" \
  --dataloader_num_workers=8 \
  --resolution=512 --center_crop --random_flip \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --max_train_steps=500 \
  --learning_rate=1e-04 \
  --max_grad_norm=1 \
  --lr_scheduler="cosine" --lr_warmup_steps=0 \
  --output_dir="./lora_weights" \
  --checkpointing_steps=500 \
  --seed=1337
